name: Python application

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          src: "./hugger"
      - uses: isort/isort-action@v1
        with:
          sort-paths: "./hugger"
  lint:
    name: Lint with ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./hugger"
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --locked --dev

      - name: Run tests
        run: uv run pytest hugger tests

  build_source_dist:
    name: Build source distribution
    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install

      - name: Build
        run: uv build

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.tar.gz

  publish:
    name: Publish package
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - format
      - lint
      - test
      - build_source_dist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ./dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # remove repository key to set the default to pypi (not test.pypi.org)
          #repository-url: https://test.pypi.org/legacy/
          user: __token__
          #password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          password: ${{ secrets.PYPI_API_TOKEN }}
